cars = [
  {
    "id": 1,
    "Brand Name": "Suzuki",
    "Body Type": "Hatchback",
    "Car Name": "Alto",
    "Engine/Hybrid/Electric": "Engine",
    "Engine Power (CC)": 658,
    "Colors Offered": "blue, grey, white, red",
    "Mileage": 18,
    "Auto/Manual": "Manual",
    "AC/Radio": "Yes",
    "Model Year": 2026,
    "Price": "32 lacs",
    "image": "https://cache4.pakwheels.com/system/car_generation_pictures/16749/medium/Cover.jpg?1768990406"
  },
  {
    "id": 2,
    "Brand Name": "Suzuki",
    "Body Type": "Hatchback",
    "Car Name": "cultus",
    "Engine/Hybrid/Electric": "Engine",
    "Engine Power (CC)": 998,
    "Colors Offered": "blue, grey, white, red",
    "Mileage": 16,
    "Auto/Manual": "auto/Manual",
    "AC/Radio": "Yes",
    "Model Year": 2026,
    "Price": "45.9 lacs",
    "image": "https://cache4.pakwheels.com/system/car_generation_pictures/6014/original/Suzuki_Cultus_-_PNG.png?1768562638"
  },
  {
    "id": 3,
    "Brand Name": "suzuki",
    "Body Type": "hatchback",
    "Car Name": "swift",
    "Engine/Hybrid/Electric": "engine",
    "Engine Power (CC)": 1197,
    "Colors Offered": "blue,red ,silver, white",
    "Mileage": "12.18",
    "Auto/Manual": "automatic",
    "AC/Radio": "yes",
    "Model Year": 2026,
    "Price": "47.39 lacs",
    "image": "https://cache4.pakwheels.com/system/car_generation_pictures/7311/original/White-Base-PS.jpg?1768566947"
  },
  {
    "id": 4,
    "Brand Name": "Toyata",
    "Body Type": "sendan",
    "Car Name": "yaris",
    "Engine/Hybrid/Electric": "engine",
    "Engine Power (CC)": "1329cc",
    "Colors Offered": "blue, grey, white,",
    "Mileage": 12,
    "Auto/Manual": "automatic",
    "AC/Radio": "Yes",
    "Model Year": 2026,
    "Price": "46.5 lacs",
    "image": "https://cache4.pakwheels.com/system/car_generation_pictures/16706/original/Cover.jpg?1768979326"
  },
  {
    "id": 5,
    "Brand Name": "Toyata",
    "Body Type": "sealon",
    "Car Name": "Grendy",
    "Engine/Hybrid/Electric": "Engine",
    "Engine Power (CC)": 1798,
    "Colors Offered": "blue, grey, white,",
    "Mileage": 15,
    "Auto/Manual": "Auto/Manual",
    "AC/Radio": "Yes",
    "Model Year": 2026,
    "Price": "82 lacs",
    "image": "https://cache1.pakwheels.com/system/car_generation_pictures/5361/original/Corolla-X-Cars-Cropped-Pictures-for-Website.jpg?1606903674"
  },
  {
    "id": 6,
    "Brand Name": "toyata",
    "Body Type": "suv",
    "Car Name": "Cross",
    "Engine/Hybrid/Electric": "Hybrid",
    "Engine Power (CC)": 1798,
    "Colors Offered": "blue, grey, white,",
    "Mileage": 12,
    "Auto/Manual": "auto",
    "AC/Radio": "yes",
    "Model Year": 2026,
    "Price": "89.5 lacs",
    "image": "https://cache2.pakwheels.com/system/car_generation_pictures/7650/original/cockpit.jpg?1768567180"
  },
  {
    "id": 7,
    "Brand Name": "Honda",
    "Body Type": "suv",
    "Car Name": "HR-V",
    "Engine/Hybrid/Electric": "engine",
    "Engine Power (CC)": "",
    "Colors Offered": "blue, grey, white,",
    "Mileage": 12,
    "Auto/Manual": "automatic",
    "AC/Radio": "yes",
    "Model Year": 2026,
    "Price": "90 lacs",
    "image": "https://cache4.pakwheels.com/system/car_generation_pictures/16746/original/Cover.jpg?1768989567"
  },
  {
    "id": 8,
    "Brand Name": "Honda",
    "Body Type": "sealon",
    "Car Name": "civic",
    "Engine/Hybrid/Electric": "Engine",
    "Engine Power (CC)": "1300cc/1500cc",
    "Colors Offered": "blue, grey, white,",
    "Mileage": 15,
    "Auto/Manual": "Auto/Manual",
    "AC/Radio": "Yes",
    "Model Year": 2026,
    "Price": "1.01 crore",
    "image": "https://cache2.pakwheels.com/system/car_generation_pictures/10345/original/Cover_%2818%29.jpg?1767275410"
  },
  {
    "id": 9,
    "Brand Name": "honda",
    "Body Type": "sedan",
    "Car Name": "City",
    "Engine/Hybrid/Electric": "Engine",
    "Engine Power (CC)": 13,
    "Colors Offered": "blue,red,white",
    "Mileage": 12,
    "Auto/Manual": "",
    "AC/Radio": "Yes",
    "Model Year": 2026,
    "Price": "4,737,000",
    "image": "https://cache1.pakwheels.com/system/car_generation_pictures/16740/original/Cover.jpg?1768988801"
  },
  {
    "id": 10,
    "Brand Name": "hyundai",
    "Body Type": "sedan",
    "Car Name": "sonata",
    "Engine/Hybrid/Electric": "Engine",
    "Engine Power (CC)": "1999cc/2497cc",
    "Colors Offered": "blue, grey, white,",
    "Mileage": 12.13,
    "Auto/Manual": "automatic",
    "AC/Radio": "Yes",
    "Model Year": 2026,
    "Price": "16,521,000",
    "image": "https://cache2.pakwheels.com/system/car_generation_pictures/8025/original/Cover.jpg?1768564613"
  },
  {
    "id": 11,
    "Brand Name": "hyundai",
    "Body Type": "sedan",
    "Car Name": "sonata n line",
    "Engine/Hybrid/Electric": "Engine",
    "Engine Power (CC)": "2497cc",
    "Colors Offered": "blue, grey, white,",
    "Mileage": 9,
    "Auto/Manual": "automatic",
    "AC/Radio": "Yes",
    "Model Year": 2026,
    "Price": "16,521,000",
    "image": "https://cache2.pakwheels.com/system/car_generation_pictures/8025/original/Cover.jpg?1768564613"
  },
  {
    "id": 12,
    "Brand Name": "hyundai",
    "Body Type": "sedan",
    "Car Name": "Elantra",
    "Engine/Hybrid/Electric": "hybride",
    "Engine Power (CC)": "1580cc",
    "Colors Offered": "blue, grey, white,",
    "Mileage": 22,
    "Auto/Manual": "automatic",
    "AC/Radio": "Yes",
    "Model Year": 2026,
    "Price": "98.95 lacs",
    "image": "https://cache1.pakwheels.com/system/car_generation_pictures/9800/original/Cover.jpg?1760439908"
  },
  {
    "id": 13,
    "Brand Name": "nissan",
    "Body Type": "suv",
    "Car Name": "nismo",
    "Engine/Hybrid/Electric": "turbo engine",
    "Engine Power (CC)": "3,492",
    "Colors Offered": "grey,whaite, black",
    "Mileage": 3.5,
    "Auto/Manual": "automatic",
    "AC/Radio": "Yes",
    "Model Year": 2026,
    "Price": "6.25 crores",
    "image": "https://cache2.pakwheels.com/system/car_generation_pictures/5740/original/nissan_note_2012.jpg?1768566137"
  },
  {
    "id": 14,
    "Brand Name": "nissan",
    "Body Type": "coupe",
    "Car Name": "z",
    "Engine/Hybrid/Electric": "turbo engine",
    "Engine Power (CC)": "3,000",
    "Colors Offered": "grey,whaite, black",
    "Mileage": "6-13kL",
    "Auto/Manual": "automatic",
    "AC/Radio": "Yes",
    "Model Year": 2026,
    "Price": "6.25 crores",
    "image": "https://cache3.pakwheels.com/ad_pictures/1408/nissan-350z-coupe-8-2004-140856601.webp"
  },
  {
    "id": 15,
    "Brand Name": "Nissan",
    "Body Type": "hatchback",
    "Car Name": "dayz",
    "Engine/Hybrid/Electric": "hybride",
    "Engine Power (CC)": "660cc",
    "Colors Offered": "",
    "Mileage": 18,
    "Auto/Manual": "automatic",
    "AC/Radio": "Yes",
    "Model Year": 2026,
    "Price": "56.5 lacs",
    "image": "https://cache2.pakwheels.com/ad_pictures/1423/nissan-dayz-x-40-2021-142353918.webp"
  },
  {
    "id": 16,
    "Brand Name": "Byd",
    "Body Type": "sedan",
    "Car Name": "seal",
    "Engine/Hybrid/Electric": "electric",
    "Engine Power (CC)": "390kW",
    "Colors Offered": "Ice Blue, Polar White, Space Black, Atlantis Grey, and Indigo Grey",
    "Mileage": 510,
    "Auto/Manual": "automatic",
    "AC/Radio": "yes",
    "Model Year": 2026,
    "Price": "16,990,000",
    "image": "https://cache3.pakwheels.com/ad_pictures/1438/byd-seal-premium-11-2025-143896187.webp"
  }
]