cars = [
  {
    "id": 1,
    "Brand Name": "Suzuki",
    "Body Type": "Hatchback",
    "Car Name": "Alto",
    "Engine/Hybrid/Electric": "Engine",
    "Engine Power (CC)": 658,
    "Colors Offered": "blue, grey, white, red",
    "Mileage": 18,
    "Auto/Manual": "Manual",
    "AC/Radio": "Yes",
    "Model Year": 2026,
    "Price": "32 lacs"
  },
  {
    "id": 2,
    "Brand Name": "Suzuki",
    "Body Type": "Hatchback",
    "Car Name": "cultus",
    "Engine/Hybrid/Electric": "Engine",
    "Engine Power (CC)": 998,
    "Colors Offered": "blue, grey, white, red",
    "Mileage": 16,
    "Auto/Manual": "auto/Manual",
    "AC/Radio": "Yes",
    "Model Year": 2026,
    "Price": "45.9 lacs"
  },
  {
    "id": 3,
    "Brand Name": "suzuki",
    "Body Type": "hatchback",
    "Car Name": "swift",
    "Engine/Hybrid/Electric": "engine",
    "Engine Power (CC)": 1197,
    "Colors Offered": "blue,red ,silver, white",
    "Mileage": "12.18",
    "Auto/Manual": "automatic",
    "AC/Radio": "yes",
    "Model Year": 2026,
    "Price": "47.39 lacs"
  },
  {
    "id": 4,
    "Brand Name": "Toyata",
    "Body Type": "hatchback",
    "Car Name": "yaris",
    "Engine/Hybrid/Electric": "engine",
    "Engine Power (CC)": "1329cc",
    "Colors Offered": "blue, grey, white,",
    "Mileage": 12,
    "Auto/Manual": "automatic",
    "AC/Radio": "Yes",
    "Model Year": 2026,
    "Price": "46.5 lacs"
  },
  {
    "id": 5,
    "Brand Name": "Toyata",
    "Body Type": "sealon",
    "Car Name": "Grendy",
    "Engine/Hybrid/Electric": "Engine",
    "Engine Power (CC)": 1798,
    "Colors Offered": "blue, grey, white,",
    "Mileage": 15,
    "Auto/Manual": "Auto/Manual",
    "AC/Radio": "Yes",
    "Model Year": 2026,
    "Price": "82 lacs"
  },
  {
    "id": 6,
    "Brand Name": "toyata",
    "Body Type": "suv",
    "Car Name": "hybride",
    "Engine/Hybrid/Electric": "engine",
    "Engine Power (CC)": 1798,
    "Colors Offered": "blue, grey, white,",
    "Mileage": 12,
    "Auto/Manual": "auto",
    "AC/Radio": "yes",
    "Model Year": 2026,
    "Price": "89.5 lacs"
  },
  {
    "id": 7,
    "Brand Name": "Honda",
    "Body Type": "suv",
    "Car Name": "",
    "Engine/Hybrid/Electric": "engine",
    "Engine Power (CC)": "",
    "Colors Offered": "blue, grey, white,",
    "Mileage": 12,
    "Auto/Manual": "automatic",
    "AC/Radio": "yes",
    "Model Year": 2026,
    "Price": "90 lacs"
  },
  {
    "id": 8,
    "Brand Name": "Honda",
    "Body Type": "sealon",
    "Car Name": "civic",
    "Engine/Hybrid/Electric": "Engine",
    "Engine Power (CC)": "1300cc/1500cc",
    "Colors Offered": "blue, grey, white,",
    "Mileage": 15,
    "Auto/Manual": "Auto/Manual",
    "AC/Radio": "Yes",
    "Model Year": 2026,
    "Price": "1.01 crore"
  },
  {
    "id": 9,
    "Brand Name": "honda",
    "Body Type": "sedan",
    "Car Name": "City",
    "Engine/Hybrid/Electric": "Engine",
    "Engine Power (CC)": 13,
    "Colors Offered": "blue,red,white",
    "Mileage": 12,
    "Auto/Manual": "",
    "AC/Radio": "Yes",
    "Model Year": 2026,
    "Price": "4,737,000"
  },
  {
    "id": 10,
    "Brand Name": "hyundai",
    "Body Type": "sedan",
    "Car Name": "sonata",
    "Engine/Hybrid/Electric": "Engine",
    "Engine Power (CC)": "1999cc/2497cc",
    "Colors Offered": "blue, grey, white,",
    "Mileage": 12.13,
    "Auto/Manual": "automatic",
    "AC/Radio": "Yes",
    "Model Year": 2026,
    "Price": "16,521,000"
  },
  {
    "id": 11,
    "Brand Name": "hyundai",
    "Body Type": "sedan",
    "Car Name": "sonata n line",
    "Engine/Hybrid/Electric": "Engine",
    "Engine Power (CC)": "2497cc",
    "Colors Offered": "blue, grey, white,",
    "Mileage": 9,
    "Auto/Manual": "automatic",
    "AC/Radio": "Yes",
    "Model Year": 2026,
    "Price": "16,521,000"
  },
  {
    "id": 12,
    "Brand Name": "hyundai",
    "Body Type": "sedan",
    "Car Name": "Elantra",
    "Engine/Hybrid/Electric": "hybride",
    "Engine Power (CC)": "1580cc",
    "Colors Offered": "blue, grey, white,",
    "Mileage": 22,
    "Auto/Manual": "automatic",
    "AC/Radio": "Yes",
    "Model Year": 2026,
    "Price": "98.95 lacs"
  },
  {
    "id": 13,
    "Brand Name": "nissan",
    "Body Type": "suv",
    "Car Name": "nismo",
    "Engine/Hybrid/Electric": "turbo engine",
    "Engine Power (CC)": "3,492",
    "Colors Offered": "grey,whaite, black",
    "Mileage": 3.5,
    "Auto/Manual": "automatic",
    "AC/Radio": "Yes",
    "Model Year": 2026,
    "Price": "6.25 crores"
  },
  {
    "id": 14,
    "Brand Name": "nissan",
    "Body Type": "coupe",
    "Car Name": "z",
    "Engine/Hybrid/Electric": "turbo engine",
    "Engine Power (CC)": "3,000",
    "Colors Offered": "grey,whaite, black",
    "Mileage": "6-13kL",
    "Auto/Manual": "automatic",
    "AC/Radio": "Yes",
    "Model Year": 2026,
    "Price": "6.25 crores"
  },
  {
    "id": 15,
    "Brand Name": "Nissan",
    "Body Type": "hatchback",
    "Car Name": "dayz",
    "Engine/Hybrid/Electric": "hybride",
    "Engine Power (CC)": "660cc",
    "Colors Offered": "",
    "Mileage": 18,
    "Auto/Manual": "automatic",
    "AC/Radio": "Yes",
    "Model Year": 2026,
    "Price": "56.5 lacs"
  },
  {
    "id": 16,
    "Brand Name": "Byd",
    "Body Type": "sedan",
    "Car Name": "seal",
    "Engine/Hybrid/Electric": "electric",
    "Engine Power (CC)": "390kW",
    "Colors Offered": "Ice Blue, Polar White, Space Black, Atlantis Grey, and Indigo Grey",
    "Mileage": 510,
    "Auto/Manual": "automatic",
    "AC/Radio": "yes",
    "Model Year": 2026,
    "Price": "16,990,000"
  }
]